---
apiVersion: v1
kind: Service
metadata:
  name: operator-demo-webhook-service
  namespace: operator-demo-system
spec:
  ports:
    - port: 443
      targetPort: 9443
      name: kubebuilder
    - port: 3443
      targetPort: 3443
      name: local
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: operator-demo-system/operator-demo-serving-cert
  creationTimestamp: null
  name: operator-demo-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: operator-demo-webhook-service
      namespace: operator-demo-system
      path: /validate-paas-dome-com-v1beta1-instance
  failurePolicy: Fail
  name: vinstance.kb.io
  rules:
  - apiGroups:
    - paas.dome.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: operator-demo-system/operator-demo-serving-cert
  creationTimestamp: null
  name: operator-demo-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: operator-demo-webhook-service
      namespace: operator-demo-system
      path: /mutate-paas-dome-com-v1beta1-instance
  failurePolicy: Fail
  name: minstance.kb.io
  rules:
  - apiGroups:
    - paas.dome.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instances
- clientConfig:
    caBundle: Cg==
    service:
      name: operator-demo-webhook-service
      namespace: operator-demo-system
      path: /pods
      port: 3443
  failurePolicy: Fail
  name: webhook.mutate.paas.demo.com
  sideEffects: None
  timeoutSeconds: 5
  rules:
  - apiGroups: [""]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["pods"]
  admissionReviewVersions: ["v1", "v1beta1"]